### ISSUE TITLE
[Enhancement] Easily access last node in TableRow class

### ISSUE THREAD

**Issue by ibeladi-mrsool** [usernane/phpStructs#6]
## Description
Make a pointer to the last node in the TableRow class in order to facilitate the setting of attributes and classes.

## Current Implementations
You need to know the index of node, which might be troublesome when adding/removing other nodes.
```
$tableRow->addCell('something');
$tableRow->children()->get(5)->setStyle(['color' => 'red']);
```
Also, this implementation, which will require more boilerplate code.
```
$tableRow->addCell('something');
$tableRow->children()->get($tableRow->childrenCount() - 1)->setStyle(['color' => 'red']);
```
## Desired Implementation
```
$tableRow->addCell('something');
$tableRow->getLastChild()->setStyle(['color' => 'red']);
```

**Comment by usernane** [comment]
Added new method to the class `HTMLNode` to do that which is `HTMLNode::getLastChild()`
